name: Update dots-website

on:
  push:
    branches:
      - master
      - website/auto-update-workflow

jobs:
  dispatch:
    name: Dispatch update
    runs-on: ubuntu-latest
    steps:
      - run: |
        curl -XPOST \
          -u "${{ secrets.PAT_DOTS_WEBSITE_USER }}:${{ secrets.PAT_DOTS_WEBSITE }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/simplysecure/dots-website/actions/workflows/update-patterns.yaml/dispatches \
          --data '{"ref": "master"}'
