name: Prettify markdown

on:
  pull_request:

jobs:
  dispatch:
    name: commit fixes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify markdown files
        uses: creyD/prettier_action@v3.2
        with:
          prettier_options: "--write **/*.md"
          commit_message: "Prettify markdown formatting"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
